modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"

[[mods]]
modId="simplesoy"
version="0.0.5-1.19.2"
displayName="Simple Soy"
logoFile="simplesoy.png"
authors="29Naybla"
description='''
Adds a soy crop, and substitues for milk and meat!
'''
[[dependencies.simplesoy]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simplesoy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
